### ISSUE TITLE
virtualenv support?

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern_aws#138]
It's not uncommon to me that python scripts fails because of lacking certain package, but the error message is not always that apparent. One example: `bin/hussh` fails because package `transit` required by `lib/redis_util.py` is not installed, but I can only see `No redis access; I won't be whitelisted in this SSH session`.

`virtualenv` + `requirements.txt` seems a good fit here. No longer need to install packages in global environment, and any new dependencies can be solved by `pip install -r requirements.txt`.

If no opposition @aranhoide I can make that simple change.

**Comment by aranhoide** [comment]
I have improved the error reporting of that particular script, which I agree was bad (it was meant for machines with no redis access).

The change you suggest looks great, though, and I have no objections to it.

**Comment by aranhoide** [comment]
@fffw: just please make sure you don't leak any secrets in the files checked in to lantern_aws.  Secrets should somehow be sourced from lantern_aws/secret (which is a checkout of too-many-secrets).
