### ISSUE TITLE
Move away users from closed proxies before retiring them for bandwidth consumption 

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#140]
When a proxy closes itself because it's hitting its monthly quota, we don't want to put all its users back in the slice table, where they are more vulnerable to infiltration and may cause imbalances.  Since the original server worked alright and was not too underutilized, a good option is to just move all its users to a server freshly pulled from the queue.

This is especially important now that we have some dedicated servers.  But this also points to a balancing issue: pouring the users of a big server into a smaller or bigger one is probably suboptimal at best.

**Comment by myleshorton** [comment]
> But this also points to a balancing issue: pouring the users of a big server into a smaller or bigger one is probably suboptimal at best.

How does #149 address that issue @aranhoide, if at all? How many dedicated servers do we have at this point?

**Comment by aranhoide** [comment]
#149 doesn't address this issue.  We have 4 dedicated servers.  They won't hit their transfer limit this month. My current plan is to offload their users manually to regular proxies. We're not seeing the kind of instability that prompted me to give these a try.

  
If and when we decide to use dedicated proxies for free users too, I don't suppose we'll keep non-dedicated ones around, so I don't see much of a point in addind logic to handle both at the same time.  We can add it when it becomes clear we'll use it.

**Comment by aranhoide** [comment]
@myleshorton correction: we used to have 5, not 4, dedicated proxies, and one of them, launched last April 20, was likely to hit bandwidth limits by the end of the month.

I've offloaded three of them, including this dangerous one.  I'll offload the other two after the server queues recover a bit (it takes some 10 regular proxies to serve the users of a dedicated one).

**Comment by aranhoide** [comment]
All dedicated proxies are offloaded and retired now.
