### ISSUE TITLE
Proxies failing proxying checks without much load

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#155]
This is happening (almost?) exclusively in Vultr.  These failures are intermittent.  A proxy may fail a couple checks from all cloudmasters in a row and go on to work normally, only to fail again sometime later.  Also, most often two proxies will more or less symultaneously start and end failing like this.

I don't remember this ever happening in DO.  Therefore, I believe that this is some problem in their datacenter.  On that assumption, I've been retiring these, so hopefully the replacing proxies are in better configured locations, have better neighbors, etc.

I've logged a ticket with Vultr about that, pointing them to a particularly clear case, and they claim that the particular proxy I've pointed them to looked like it was working optimally during the time of the report.  They asked me to keep informing them of any further failures, attaching both outgoing and incoming `mtr` reports.

In a particularly bad case since this happened, I've found some 5% packet loss exiting Japan.  I don't think I caught the issue red handed.  I'll keep trying.  In the meanwhile, I'm opening this one to keep track of progress.

**Comment by aranhoide** [comment]
I was wondering whether this had anything to do with the position of these proxies in the list of fallbacks to check (`fallbacks_to_check.json` in the cloudmasters), the hypothesis being that there are many proxies which would have response times close to the timeout, but some of them would actually time out more often than others because of something related to the order in which we tried them.

So I looked at the three ones which have been failing most often.  Their indices in that list are 474, 900, and 1134 (of a total 1949), so this doesn't seem a promising line of investigation.

**Comment by aranhoide** [comment]
One of these proxies is failing checks performed from the very data center it's in, so mtr may not be the most illuminating diagnosing tool for this.

**Comment by aranhoide** [comment]
Vultr claims this is a routing issue upstream from them and that they're working on that.

**Comment by oxtoacart** [comment]
Doesn't appear to be happening at the moment.
