### ISSUE TITLE
Our baked-in fallbacks are no longer ours

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern_aws#209]
45.32.60.31 and 45.55.184.76

Whoever owns these IPs now may think that they're getting DDOS'ed by us.  Not to mention that our clients will get errors trying to talk to them.

I think we should:

1) Put in place some guards to prevent this in the future
2) Use floating IPs so that if we lose the individual server for some reason, we can keep the same configuration on the clients

cc: @aranhoide @myleshorton

**Comment by oxtoacart** [comment]
Looks like this was lost in the Vultr retirement.  We should probably replace it with an SFO server I guess?

**Comment by oxtoacart** [comment]
I removed the bad fallback from the built-in config here - https://github.com/getlantern/lantern/pull/4520

Ideally, we should replace it with an SFO-based server.

**Comment by aranhoide** [comment]
We do have some guard for automatic destruction of baked-in proxies.  I've just tested that and it's working well.

So the most likely cause of this is manual deletion.  That is certainly the case for the Vultr one; I manually deleted the last few proxies that didn't get killed when I retired the Vultrs.

As for the floating IPs that seems like a good idea, although of course those IPs are likely to get blocked, at least in times of high censor activity.  Maybe we should start by setting a few of those manually, and if they work well we automate it?

**Comment by aranhoide** [comment]
@oxtoacart: I'll close this one since we can't do much about manual deletion other than remember not to do it or at least double-check for baked-in proxies and document these ops somewhere.  Feel free to open a new ticket for the floating IPs.

**Comment by oxtoacart** [comment]
@aranhoide Where are we tracking the setup of new baked-in fallbacks?
