### ISSUE TITLE
In production, stunnel is consuming more than twice as much CPU as Redis

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern_aws#214]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1447 root      20   0 4192400  25700   1640 S 246.4  0.2  13:12.12 stunnel4
10493 redis     20   0 2670860 2.521g   1448 R  95.9 16.1   3:51.48 redis-server
```

**Comment by aranhoide** [comment]
Is CPU the bottleneck?  Or do we have enough of it in the DO sizes we need for the redis RAM anyway?

**Comment by oxtoacart** [comment]
CPU is the bottleneck.  I had to upsize to a 16GB instance just to get enough CPU.

This option for stunnel looks promising - sessionCacheSize  I think by default it's not using session caching.

Also, our proxies aren't using session caching - https://github.com/getlantern/http-proxy-lantern/blob/master/redis/redis.go#L96  Fixing that should make a big difference I think.

**Comment by oxtoacart** [comment]
Interestingly, now that the system has been up for a while, stunnel CPU usage is down to half of Redis cpu usage, so perhaps this is only a problem after Redis restarts.

**Comment by myleshorton** [comment]
Any more thoughts on this one @oxtoacart? Should I move it to the backlog and out of TO-DO?

**Comment by oxtoacart** [comment]
It's really just a cost-saving measure.  To put it in perspective, our master redis instance is costing us $160 per month right now.  Once we implement auto-failover, our backup redis instance will cost the same, so we're looking at $320 per month.  Right now, CPU usage is peaking at 40%, so we have some room to grow.

**Comment by oxtoacart** [comment]
Unfortunately, it looks like session caching is already enabled and working for stunnel.  When I turn up debug logging for stunnel, I see this:

```
SSL connected: previous session reused
```

**Comment by myleshorton** [comment]
Seems like there's not much more we can do on this one right @oxtoacart?

**Comment by oxtoacart** [comment]
Yeah, Redis is holding up even with bandwidth tracking on, so I say we close for now.
