### ISSUE TITLE
Enable Pro features (token retrieval and pro-server communication)

### ISSUE THREAD

**Issue by uaalto** [getlantern/lantern_aws#225]

**Comment by myleshorton** [comment]
Can you elaborate on this one a little bit @uaalto? When are these needed?

**Comment by uaalto** [comment]
This is a simple fix. It turns out that along the lines of https://github.com/getlantern/http-proxy-lantern/issues/96, we didn't test Pro users properly yet, so I did some end-to-end testing of this and realized that in staging, our proxies don't have the proper flag enabled to handle Pro users properly.
In a nutshell: our servers currently are free-only.

**Comment by uaalto** [comment]
Is this deployed @oxtoacart ?

**Comment by oxtoacart** [comment]
In progress.

**Comment by oxtoacart** [comment]
@uaalto Just turning on the enablepro flag wasn't enough, as we need to give the servers their ID.  Is the ID just the hostname?  Could we just grab that in the code using `os.Hostname()`?

**Comment by aranhoide** [comment]
@oxtoacart in the context of Pro the ID is the Salt-given name of the machine (e.g., good old `fp-https-doams3-20160513-006`).  I think it's the same as the hostname for all of our current machines, so `os.Hostname()` might work.  Anyway, the idiomatic way to get it in a salt config is with `{{ grains['id'] }}`.

**Comment by oxtoacart** [comment]
Thanks @aranhoide!

@uaalto I'll go ahead and make the necessary changes.

**Comment by oxtoacart** [comment]
The PR is still being reviewed, but I went ahead and deployed the binary to all 3 regions in staging.

**Comment by myleshorton** [comment]
Is this one all set too @oxtoacart?

**Comment by oxtoacart** [comment]
Yup.
