### ISSUE TITLE
cert error in offload_users script

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern_aws#237]
This happens every time at the end:

```
Unable to check whitelisted status, assuming whitelisted:  [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by aranhoide** [comment]
Thanks!  This is probably the ops panel letsencrypt cert expiring.  I'll take the chance to make an auto-renew script.

https://github.com/getlantern/ops-panel/issues/3

**Comment by aranhoide** [comment]
Ops panel had indeed expired (tested by just browsing to it).  It's now fixed, and auto-renew now runs in a weekly cron job in the ops panel.
