### ISSUE TITLE
Remove cloudmaster from the critical path for building install wrappers

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern_aws#24]
Right now, the controller sends messages for building install wrappers to the same queue that's used for launching new VMs, which is read by the cloudmaster.  The cloudmaster then delegates these messages to the wrapper_builder VMs.

More efficient, and faster, would be to have the wrapper_builder VMs poll these messages themselves.  This requires:

1. Setting up a new queue
2. Having the controller send install wrapper requests to the new queue
3. Having the wrapper_builder VMs poll this queue directly (make sure that we can safely have multiple workers polling the same queue)
4. Remove the functionality from the cloudmaster for processing installer wrapper messages

**Comment by aranhoide** [comment]
Obsolete; wrappers are no more.
