### ISSUE TITLE
Check for sha before downloading/replacing http-proxy binary

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#74]
We currently download the http-binary unconditionally whenever we apply salt state.  We also replace our current copy of it with the one we just downloaded without checking for integrity.

Besides being somewhat inefficient, this is error prone.  While I manually check for bad binaries whenever upgrading http-proxy, I could forget about this when deploying unrelated config updates.

So we should include the sha of http-proxy in the salt config, such that we don't download it again if it's already the configured version, and more importantly, so we don't install a broken download.

**Comment by aranhoide** [comment]
Fixed in https://github.com/getlantern/lantern_aws/commit/3414d8f841826c274b263bcbc3b3747754b1a3f4

**Comment by myleshorton** [comment]
Nice! Is there any way to specify something like If-Modified here?

**Comment by aranhoide** [comment]
I'm not sure, since we also change the URL when we upgrade versions?
