### ISSUE TITLE
disks full in Vultr Tokyo machines

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#85]
Last time I looked into this, the logrotate configuration seemed alright out of the box in both DO and Vultr.  But Vultr machines keep breaking because of full disks, and /var/log/syslog seems the main culprit.

**Comment by myleshorton** [comment]
Is this one anyone needs to take immediate action on @aranhoide?

**Comment by aranhoide** [comment]
I'm just retiring the machines that get affected by this because they are few enough, and it makes sense anyway to gradually transition into DO Singapore, which has other advantages.  So it's not urgent, but if anyone has the time it would help, yes.  Otherwise it's possible that this will be affecting our VPSs from Frankfurt a few months from now.

**Comment by aranhoide** [comment]
So it seems this wasn't a matter of slowly accruing syslogs, but of one day's worth of logs being too much for the proxy.  See https://github.com/getlantern/lantern_aws/issues/85

**Comment by aranhoide** [comment]
Fixed by https://github.com/getlantern/lantern_aws/pull/96
