### ISSUE TITLE
95/100% CPU syndrome

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#90]
I've been observing this in a very small proportion of our VPSs.  They would just suddenly start consuming between 95% and 100% CPU and stop all network activity.  They wouldn't even accept SSH logins.

AFAICT it started happening after the Golang-based http-proxy was released.  Anecdotally, my impression is that it seems to happen more often after reboots and Salt deployments.  I may be wrong about both accounts.

**Comment by aranhoide** [comment]
I'm not giving this a super high priority because this is only one of the reasons why a small fraction of our proxy would fail and need to be retired.

**Comment by fffw** [comment]
Using the [`dd`+`bzip` trick](https://github.com/getlantern/http-proxy-lantern/pull/38#issuecomment-192554118) I simulated 100% CPU on VPS but the network performance was not affected at all. It gives me an impression that we can't even make a VPS unresponsive from user space.

There are reports that hypervisor, whether it's XEN or KVM, can suddenly hang guest OS. Could it be the reason?

**Comment by aranhoide** [comment]
@fffw very interesting, thanks!

A quick googling turned up this, but maybe it doesn't mean much; there are a number of reasons why a CPU might get pegged.

https://www.digitalocean.com/community/questions/how-can-i-find-out-why-my-cpu-is-spiking-to-100

I'll try asking DO support next time this happens.

**Comment by aranhoide** [comment]
I haven't seen this for a while.  Also, according to @fffw, it's possible that we can't do much about this but retire the proxies where it happens.  These are easy to spot because they fail proxying checks.
