### ISSUE TITLE
Overwhelmed proxy will push much less traffic than an optimally utilized one

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern_aws#91]
I've been observing this in fallback proxies (the ones serving people that can't get a custom one for any reason).  See, for example (as of this writing):

https://cloud.digitalocean.com/droplets/11032299#actions-graphs

This is failing checkfallbacks currently, but it's pushing much less traffic than at its peak, and it's not even that highly loaded.  Load average is under 1 and both CPU and RAM are under 50%.

It would be really nice to find out why this happens, because this complicates the relation between machine load, throughput, and QoS, which could mess with any automated load balancing systems we develop based on these server-side metrics.

**Comment by myleshorton** [comment]
More current example:

https://cloud.digitalocean.com/droplets/11378840#actions-graphs

It's interesting there's so much disk activity.

**Comment by myleshorton** [comment]
Here's the grafana info:

https://dashboard.getlantern.org/dashboard/script/single-proxy.js?name=fp-dosgp1-20160223-242

**Comment by myleshorton** [comment]
On the default fallback CPU was spiking over 100%, so could be related.

**Comment by myleshorton** [comment]
This is a quad-core machine, however, so this should be able to handle up to 400% CPU, so that appears to not be the issue...

**Comment by myleshorton** [comment]
See https://github.com/getlantern/lantern/issues/3754 and https://github.com/getlantern/lantern/issues/3753

**Comment by aranhoide** [comment]
A full disk explains the behavior of the proxy linked by @myleshorton, but not that of the fallback proxy.

**Comment by myleshorton** [comment]
Yeah just to keep track of this, the default fallback proxy was getting i/o timeouts.

**Comment by aranhoide** [comment]
A workaround for this might be observing the ratio of inbound to outbound transfer.  If these diverge, this may be a sign of trouble.  See, for example, this graph:

https://cloud.digitalocean.com/droplets/11983576#actions-graphs

High system CPU consumption and disk activity (and proxying check failures) seem correlated with outbound transfer falling behind inbound one.  Of course, in this particular case we could have observed CPU consumption and disk activity by themselves, but these don't always happen when a system is overloaded.  Maybe the in vs out ratio still happens when everything else seems normal?

**Comment by myleshorton** [comment]
Interesting @aranhoide. Maybe keep observing and see if that theory holds
up?

**Comment by aranhoide** [comment]
Another thing to watch might be ping time to server.  IIRC that was observed to be a good predictor of performance, so it's what the client will be using.  I'm not sure whether this holds true for overloaded servers too, but worth a try.

**Comment by aranhoide** [comment]
I'll close this bug because recently I'm not seeing this condition as stated in <=2GB machines.  The related fact that we don't get any more throughput for >2GB machines is of no much practical relevance currently, since we can scale horizontally in all cases and the sweet spot seems to be at 1GB anyway.

In all <=2GB servers I've seen for a while, disk activity and system CPU seems to correlate well with overloading, so we can just use those, and not bandwidth, to trigger adjustments in individual proxies.  This will not help as much with spreading load across proxies, but let's just make sure no proxies are overloaded, then split load according to transfer.
